# Site settings
title: Wilfred
description: 'There is nothing.'
url: 'https://WilfredShen.cn'
baseurl: ''
srcurl: '/static'
imgrepo: 'https://WilfredShen.cn/static/images'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Wilfred Shen'
  email: WilfredShen@tom.com
  # twitter_username: WilfredShen
  # facebook_username: WilfredShen
  github_username:  WilfredShen
  # linkedin_username:  WilfredShen

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

# Build settings
destination: _site
paginate: 10
paginate_path: "blog/page:num"
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  syntax_highlighter: rouge

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
